spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springuser
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    url: jdbc:mysql://mysql:3306/db_example
    # url: jdbc:mysql://0.0.0.0:3306/db_example
    password: ThePassword
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
